---
- hosts: all
  gather_facts: no
  vars_prompt:
    - name: "host"
      prompt: "please enter the target hostname from: {{ ansible_play_hosts }}"
      private: no
  tasks:
    - add_host:
        name: "{{ host }}"
        groups: chosen_host

- name: The playbook for configuring the system
  hosts: chosen_host
  become: yes
  vars_prompt:
    - name: "use_external_containerd"
      prompt: "Do you want to use external containerd? (yes/no)"
      private: no
      default: "no"
    - name: "new_hostname"
      prompt: "Please enter the new hostname for the server or enter to skip."
      private: no
      default: ""

  tasks:
    - name: Check operating system
      fail:
        msg: "This playbook can only be run on CentOS, AlmaLinux or Rocky Linux."
      when: ansible_distribution not in ['CentOS', 'AlmaLinux', 'Rocky']

    - name: Set hostname permanently
      hostname:
        name: "{{ new_hostname }}"
      when: new_hostname != ""

    - name: Disable SELinux
      block:
        - name: Check if SELinux is enforcing
          command: getenforce
          register: selinux_status
          changed_when: False

        - name: Disable SELinux if it is enforcing
          block:
            - name: Set SELinux to Permissive
              command: setenforce 0

            - name: Make SELinux change persistent
              lineinfile:
                path: /etc/selinux/config
                regexp: '^SELINUX='
                line: 'SELINUX=disabled'
          when: selinux_status.stdout == "Enforcing"

    - name: Configure io watcher
      sysctl:
        name: fs.inotify.max_user_instances
        value: '8192'
        state: present
        reload: yes

    - name: Configure DNF
      block:
        - name: Enable crb on DNF
          command: dnf config-manager --set-enabled crb

        - name: Install EPEL
          dnf:
            name:
              - epel-release
            state: latest

        - name: Install packages
          dnf:
            name:
              - openssh-server
              - zsh
              - git
              - vim
              - curl
              - wget
              - htop
              - net-tools
              - iftop
              - dnsutils
              - nfs-utils
              - tmux
              - cockpit
              - iscsi-initiator-utils # for longhorn
              - cryptsetup # for longhorn
              - jq # for longhorn check script
            state: latest

    - name: Configure Containerd
      block:
        - name: Configure external containerd
          block:
            - name: Add Docker repo
              command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

            - name: Install containerd.io
              command: dnf install containerd.io -y

            - name: Enable and start containerd service
              systemd:
                name: containerd
                state: started
                enabled: yes

            - name: Configure Containerd
              command: containerd config default > /etc/containerd/config.toml
          when: use_external_containerd | lower == "yes"

    - name: Enable and start ISCSI
      systemd:
        name: iscsid
        state: started
        enabled: yes

    - name: Configure Cockpit
      systemd:
        name: cockpit.socket
        state: started
        enabled: yes

    - name: Create NetworkManager configuration file
      copy:
        dest: /etc/NetworkManager/conf.d/rke2-canal.conf
        content: |
          [keyfile]
          unmanaged-devices=interface-name:cali*;interface-name:flannel*
        owner: root
        group: root
        mode: '0644'

    - name: Reload NetworkManager
      systemd:
        name: NetworkManager
        state: reloaded

    - name: Disable firewalld # firewalld is incompatible with Calico
      systemd:
        name: firewalld
        state: stopped
        enabled: no