---
- hosts: all
  gather_facts: no
  vars_prompt:
    - name: "agent_host"
      prompt: "please enter the rke2 agent hostname from: {{ ansible_play_hosts }}, this is the target host for the agent installation"
      private: no

    - name: "server_host"
      prompt: "please enter the rke2 server hostname from: {{ ansible_play_hosts }}, this is the already installed server hostname"
      private: no
  tasks:
    - add_host:
        name: "{{ agent_host }}"
        groups: chosen_agent_host
    - add_host:
        name: "{{ server_host }}"
        groups: chosen_server_host

- hosts: chosen_server_host
  become: yes
  tasks:
    - name: Fetch the node token from the server
      shell: cat /var/lib/rancher/rke2/server/node-token
      register: token_result

    - name: Set a fact for the token
      set_fact:
        rke2_token: "{{ token_result.stdout }}"

    - name: add variables to dummy host
      add_host:
        name: "token_var_holder"
        value: "{{ rke2_token }}"

- hosts: chosen_agent_host
  become: yes
  vars_prompt:
    - name: "SERVER_HOSTNAME"
      prompt: "What is the server hostname (reachable from agent)"
      private: no

    - name: "USE_EXTERNAL_CONTAINERD"
      prompt: "Do you want to use external containerd? (yes/no)"
      private: no
      default: "no"

    - name: "rke2_version"
      prompt: "Enter RKE2 version"
      default: "v1.25.11+rke2r1"
      private: no

  tasks:
    - name: Check operating system
      fail:
        msg: "This playbook can only be run on CentOS, AlmaLinux or Rocky Linux."
      when: ansible_distribution not in ['CentOS', 'AlmaLinux', 'Rocky']

    - name: Check if /usr/bin/rke2 exists
      stat:
        path: /usr/bin/rke2
      register: rke2_result

    - name: Install RKE2
      shell: |
        curl -sfL https://rancher-mirror.rancher.cn/rke2/install.sh | INSTALL_RKE2_MIRROR=cn INSTALL_RKE2_TYPE="agent" INSTALL_RKE2_VERSION={{ rke2_version }} sh -
      args:
        executable: /bin/bash
      when: rke2_result.stat.exists == False

    - name: Configure Rancher
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          server: https://{{ SERVER_HOSTNAME }}:9345
          token: {{ hostvars['token_var_holder']['value'] }}
          kubelet-arg: "--max-pods=200"
          container-runtime-endpoint: unix:///run/containerd/containerd.sock
      when: USE_EXTERNAL_CONTAINERD == "yes"

    - name: Configure Rancher without external containerd
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          server: https://{{ SERVER_HOSTNAME }}:9345
          token: {{ hostvars['token_var_holder']['value'] }}
          kubelet-arg: "--max-pods=200"
      when: USE_EXTERNAL_CONTAINERD == "no"

    - name: Prepare images
      shell: |
        ctr -n k8s.io image pull docker.io/rancher/pause:3.6
        ctr -n k8s.io image tag docker.io/rancher/pause:3.6 registry.k8s.io/pause:3.6
      when: USE_EXTERNAL_CONTAINERD == "yes"

    - name: Enable RKE2 Agent service
      systemd:
        name: rke2-agent.service
        enabled: yes
        # state: started

    - debug:
        msg: "RKE2 Agent installed successfully, you can start the agent manually by running 'systemctl start rke2-agent.service'"
...
