apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oidcconfigs.clpl.davidliyutong.github.io
spec:
  group: clpl.davidliyutong.github.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              baseURL:
                type: string
              authorizationURL:
                type: string
              tokenURL:
                type: string
              userInfoURL:
                type: string
              logoutURL:
                type: string
              jwksURL:
                type: string
              clientID:
                type: string
              clientSecret:
                type: string
              frontendLoginURL:
                type: string
              name:
                type: string
              redirectURL:
                type: string
              scopes:
                type: array
                items:
                  type: string
              scopeDelimiter:
                type: string
              responseType:
                type: string
              grantType:
                type: string
              userFilter:
                type: string
              userInfoPath:
                type: string
              usernamePath:
                type: string
              emailPath:
                type: string
  scope: Namespaced
  names:
    plural: oidcconfigs
    singular: oidcconfig
    kind: OIDCConfig
    shortNames:
    - oc
