apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: siteconfigs.clpl.davidliyutong.github.io
spec:
  group: clpl.davidliyutong.github.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              coderHostname:
                type: string
              coderTLSSecret:
                type: string
              vncHostname:
                type: string
              vncTLSSecret:
                type: string
              sshHostname:
                type: string
              sshTLSSecret:
                type: string
              authEndpoint:
                type: string
              nginxClass:
                type: string
  scope: Namespaced
  names:
    plural: siteconfigs
    singular: siteconfig
    kind: SiteConfig